### ISSUE TITLE
texstudio编译报错是哪里有问题呢

### ISSUE THREAD

**Issue by ujust4fun** [GouMinghao/new_SJTU_thesis_template#2]
报错指令：
line 72,  Undefined control sequence. \setmainfont
line 72,  Missing \begin{document}. \setmainfont{T

po主可否改进一下这个小问题呢😀

**Comment by GouMinghao** [comment]
这个要使用XeLaTeX进行编译，默认可能使用的是PDFLaTeX，可以检查一下是不是这个问题

**Comment by ujust4fun** [comment]
谢谢回答。
更换为xelatex后就没有问题了。🥰
