### ISSUE TITLE
学校给的latex模板和word模板不一致

### ISSUE THREAD

**Issue by LeeBY68** [GouMinghao/new_SJTU_thesis_template#4]
首先非常感谢作者提供可以成功编译的latex模板！

请问作者是否发现：学校给的latex和word模板不一致，首先封面就区别很大：latex校徽大word校徽小很多；latex没有”学位类型“而word版有....

请问作者是已经毕业了吗？使用latex版本交上去是否有问题？

**Comment by GouMinghao** [comment]
我已经毕业了，其实没关系，毕业论文的格式大致满足即可，老师不会特别关心这种死的格式

**Comment by LeeBY68** [comment]
了解了，谢谢作者！
